apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: asap

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres/
  - redis/
  - api/
  - worker/
  - web/
  - sites/
  - accounts/

commonLabels:
  app.kubernetes.io/part-of: asap-platform
  app.kubernetes.io/managed-by: kustomize
