apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: asap-api-hpa
  namespace: asap
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: asap-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: asap-web-hpa
  namespace: asap
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: asap-web
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: asap-sites-hpa
  namespace: asap
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: asap-sites
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
