use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

/// Portfolio status enum
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum PortfolioStatus {
    Draft,
    Published,
}

impl Default for PortfolioStatus {
    fn default() -> Self {
        Self::Draft
    }
}

/// Portfolio represents the structure of a user's portfolio
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Portfolio {
    pub id: Uuid,
    pub tenant_id: Uuid,
    pub slug: String,
    pub title: String,
    pub tagline: String,
    pub status: PortfolioStatus,
    pub metadata: serde_json::Value,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// PortfolioData contains the content generated by modules
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortfolioData {
    pub portfolio_id: Uuid,
    pub data: serde_json::Value,
    pub updated_at: DateTime<Utc>,
}

impl PortfolioData {
    pub fn new(portfolio_id: Uuid) -> Self {
        Self {
            portfolio_id,
            data: serde_json::json!({}),
            updated_at: Utc::now(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_portfolio_status_default() {
        assert_eq!(PortfolioStatus::default(), PortfolioStatus::Draft);
    }

    #[test]
    fn test_portfolio_status_serialization() {
        let status = PortfolioStatus::Draft;
        let serialized = serde_json::to_string(&status).unwrap();
        assert_eq!(serialized, "\"draft\"");

        let status = PortfolioStatus::Published;
        let serialized = serde_json::to_string(&status).unwrap();
        assert_eq!(serialized, "\"published\"");
    }

    #[test]
    fn test_portfolio_creation() {
        let id = Uuid::new_v4();
        let tenant_id = Uuid::new_v4();
        let slug = "my-portfolio".to_string();
        let title = "My Portfolio".to_string();
        let tagline = "A great portfolio".to_string();

        let portfolio = Portfolio {
            id,
            tenant_id,
            slug: slug.clone(),
            title: title.clone(),
            tagline: tagline.clone(),
            status: PortfolioStatus::Draft,
            metadata: serde_json::json!({}),
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };

        assert_eq!(portfolio.id, id);
        assert_eq!(portfolio.slug, slug);
        assert_eq!(portfolio.title, title);
        assert_eq!(portfolio.tagline, tagline);
        assert_eq!(portfolio.status, PortfolioStatus::Draft);
    }

    #[test]
    fn test_portfolio_status_transitions() {
        let mut portfolio = Portfolio {
            id: Uuid::new_v4(),
            tenant_id: Uuid::new_v4(),
            slug: "test".to_string(),
            title: "Test".to_string(),
            tagline: "Test".to_string(),
            status: PortfolioStatus::Draft,
            metadata: serde_json::json!({}),
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };

        assert_eq!(portfolio.status, PortfolioStatus::Draft);
        portfolio.status = PortfolioStatus::Published;
        assert_eq!(portfolio.status, PortfolioStatus::Published);
    }

    #[test]
    fn test_portfolio_with_metadata() {
        let mut portfolio = Portfolio {
            id: Uuid::new_v4(),
            tenant_id: Uuid::new_v4(),
            slug: "test".to_string(),
            title: "Test".to_string(),
            tagline: "Test".to_string(),
            status: PortfolioStatus::Draft,
            metadata: serde_json::json!({
                "theme": "dark",
                "layout": "grid"
            }),
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };

        assert_eq!(portfolio.metadata["theme"], "dark");
        assert_eq!(portfolio.metadata["layout"], "grid");
    }

    #[test]
    fn test_portfolio_data_creation() {
        let portfolio_id = Uuid::new_v4();
        let portfolio_data = PortfolioData::new(portfolio_id);

        assert_eq!(portfolio_data.portfolio_id, portfolio_id);
        assert_eq!(portfolio_data.data, serde_json::json!({}));
    }

    #[test]
    fn test_portfolio_data_with_content() {
        let portfolio_id = Uuid::new_v4();
        let mut portfolio_data = PortfolioData::new(portfolio_id);

        portfolio_data.data = serde_json::json!({
            "projects": [
                {"name": "Project 1", "description": "A great project"},
                {"name": "Project 2", "description": "Another project"}
            ],
            "bio": "I am a developer"
        });

        assert_eq!(portfolio_data.data["projects"].as_array().unwrap().len(), 2);
        assert_eq!(portfolio_data.data["bio"], "I am a developer");
    }

    #[test]
    fn test_portfolio_data_serialization() {
        let portfolio_id = Uuid::new_v4();
        let mut portfolio_data = PortfolioData::new(portfolio_id);
        portfolio_data.data = serde_json::json!({
            "title": "My Portfolio",
            "sections": ["about", "projects", "contact"]
        });

        let serialized = serde_json::to_string(&portfolio_data).unwrap();
        let deserialized: PortfolioData = serde_json::from_str(&serialized).unwrap();

        assert_eq!(deserialized.portfolio_id, portfolio_id);
        assert_eq!(deserialized.data["title"], "My Portfolio");
    }

    #[test]
    fn test_portfolio_clone() {
        let portfolio = Portfolio {
            id: Uuid::new_v4(),
            tenant_id: Uuid::new_v4(),
            slug: "test".to_string(),
            title: "Test".to_string(),
            tagline: "Test".to_string(),
            status: PortfolioStatus::Published,
            metadata: serde_json::json!({"theme": "light"}),
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };

        let cloned = portfolio.clone();
        assert_eq!(portfolio.id, cloned.id);
        assert_eq!(portfolio.slug, cloned.slug);
        assert_eq!(portfolio.status, cloned.status);
    }
}
