use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

/// Portfolio status enum
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum PortfolioStatus {
    Draft,
    Published,
}

impl Default for PortfolioStatus {
    fn default() -> Self {
        Self::Draft
    }
}

/// Portfolio represents the structure of a user's portfolio
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Portfolio {
    pub id: Uuid,
    pub tenant_id: Uuid,
    pub slug: String,
    pub title: String,
    pub tagline: String,
    pub status: PortfolioStatus,
    pub metadata: serde_json::Value,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// PortfolioData contains the content generated by modules
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortfolioData {
    pub portfolio_id: Uuid,
    pub data: serde_json::Value,
    pub updated_at: DateTime<Utc>,
}

impl PortfolioData {
    pub fn new(portfolio_id: Uuid) -> Self {
        Self {
            portfolio_id,
            data: serde_json::json!({}),
            updated_at: Utc::now(),
        }
    }
}
