use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

/// Website creation mode
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum CreationMode {
    /// Created from scratch by the user
    FromScratch,
    /// Created from a preset template
    FromPreset,
}

impl Default for CreationMode {
    fn default() -> Self {
        Self::FromScratch
    }
}

/// Website status enum
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum WebsiteStatus {
    Draft,
    Published,
}

impl Default for WebsiteStatus {
    fn default() -> Self {
        Self::Draft
    }
}

/// Website represents an account's website that can combine multiple modules
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Website {
    pub id: Uuid,
    pub account_id: Uuid,
    pub slug: String,
    pub title: String,
    pub tagline: String,
    pub status: WebsiteStatus,
    pub creation_mode: CreationMode,
    pub preset_id: Option<Uuid>,
    pub metadata: serde_json::Value,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// WebsiteData contains the content generated by modules
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteData {
    pub website_id: Uuid,
    pub data: serde_json::Value,
    pub updated_at: DateTime<Utc>,
}

impl WebsiteData {
    pub fn new(website_id: Uuid) -> Self {
        Self {
            website_id,
            data: serde_json::json!({}),
            updated_at: Utc::now(),
        }
    }
}

/// Extension represents an available extension in the system catalog
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Extension {
    pub id: Uuid,
    pub name: String,
    pub slug: String,
    pub version: String,
    pub description: String,
    pub category: String,
    pub enabled: bool,
    pub default_settings: serde_json::Value,
    pub created_at: DateTime<Utc>,
}

/// WebsiteExtension represents an activated extension for a specific website
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteExtension {
    pub id: Uuid,
    pub website_id: Uuid,
    pub extension_id: Uuid,
    pub settings: serde_json::Value,
    pub enabled: bool,
    pub activated_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// Section type for website content blocks
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum SectionType {
    Hero,
    About,
    Projects,
    Skills,
    Experience,
    Education,
    Contact,
    Blog,
    Gallery,
    Testimonials,
    Services,
    Pricing,
    Faq,
    Custom,
}

impl Default for SectionType {
    fn default() -> Self {
        Self::Custom
    }
}

/// Section layout options
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum SectionLayout {
    Full,
    Split,
    Grid,
    List,
    Cards,
    Timeline,
    Custom,
}

impl Default for SectionLayout {
    fn default() -> Self {
        Self::Full
    }
}

/// WebsiteSection represents a content block within a website
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteSection {
    pub id: Uuid,
    pub website_id: Uuid,
    pub module_id: Option<Uuid>,
    pub section_type: SectionType,
    pub slug: String,
    pub title: String,
    pub order: i32,
    pub layout: SectionLayout,
    pub settings: serde_json::Value,
    pub data: serde_json::Value,
    pub visible: bool,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// Preset configuration for auto-setup
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PresetConfig {
    pub modules: Vec<String>,
    pub sections: Vec<PresetSectionConfig>,
    pub default_settings: serde_json::Value,
}

/// Section configuration within a preset
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PresetSectionConfig {
    pub section_type: SectionType,
    pub slug: String,
    pub title: String,
    pub order: i32,
    pub layout: SectionLayout,
    pub settings: serde_json::Value,
}

/// Preset represents a template for quick website creation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Preset {
    pub id: Uuid,
    pub name: String,
    pub slug: String,
    pub description: String,
    pub category: String,
    pub config: PresetConfig,
    pub thumbnail_url: Option<String>,
    pub enabled: bool,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_website_status_default() {
        assert_eq!(WebsiteStatus::default(), WebsiteStatus::Draft);
    }

    #[test]
    fn test_website_status_serialization() {
        let status = WebsiteStatus::Draft;
        let serialized = serde_json::to_string(&status).unwrap();
        assert_eq!(serialized, "\"draft\"");

        let status = WebsiteStatus::Published;
        let serialized = serde_json::to_string(&status).unwrap();
        assert_eq!(serialized, "\"published\"");
    }

    #[test]
    fn test_creation_mode_default() {
        assert_eq!(CreationMode::default(), CreationMode::FromScratch);
    }

    #[test]
    fn test_creation_mode_serialization() {
        let mode = CreationMode::FromScratch;
        let serialized = serde_json::to_string(&mode).unwrap();
        assert_eq!(serialized, "\"from_scratch\"");

        let mode = CreationMode::FromPreset;
        let serialized = serde_json::to_string(&mode).unwrap();
        assert_eq!(serialized, "\"from_preset\"");
    }

    #[test]
    fn test_website_creation() {
        let id = Uuid::new_v4();
        let account_id = Uuid::new_v4();
        let slug = "my-website".to_string();
        let title = "My Website".to_string();
        let tagline = "A great website".to_string();

        let website = Website {
            id,
            account_id,
            slug: slug.clone(),
            title: title.clone(),
            tagline: tagline.clone(),
            status: WebsiteStatus::Draft,
            creation_mode: CreationMode::FromScratch,
            preset_id: None,
            metadata: serde_json::json!({}),
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };

        assert_eq!(website.id, id);
        assert_eq!(website.slug, slug);
        assert_eq!(website.title, title);
        assert_eq!(website.tagline, tagline);
        assert_eq!(website.status, WebsiteStatus::Draft);
        assert_eq!(website.creation_mode, CreationMode::FromScratch);
        assert!(website.preset_id.is_none());
    }

    #[test]
    fn test_website_from_preset() {
        let preset_id = Uuid::new_v4();
        let website = Website {
            id: Uuid::new_v4(),
            account_id: Uuid::new_v4(),
            slug: "test".to_string(),
            title: "Test".to_string(),
            tagline: "Test".to_string(),
            status: WebsiteStatus::Draft,
            creation_mode: CreationMode::FromPreset,
            preset_id: Some(preset_id),
            metadata: serde_json::json!({}),
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };

        assert_eq!(website.creation_mode, CreationMode::FromPreset);
        assert_eq!(website.preset_id, Some(preset_id));
    }

    #[test]
    fn test_website_status_transitions() {
        let mut website = Website {
            id: Uuid::new_v4(),
            account_id: Uuid::new_v4(),
            slug: "test".to_string(),
            title: "Test".to_string(),
            tagline: "Test".to_string(),
            status: WebsiteStatus::Draft,
            creation_mode: CreationMode::FromScratch,
            preset_id: None,
            metadata: serde_json::json!({}),
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };

        assert_eq!(website.status, WebsiteStatus::Draft);
        website.status = WebsiteStatus::Published;
        assert_eq!(website.status, WebsiteStatus::Published);
    }

    #[test]
    fn test_website_with_metadata() {
        let website = Website {
            id: Uuid::new_v4(),
            account_id: Uuid::new_v4(),
            slug: "test".to_string(),
            title: "Test".to_string(),
            tagline: "Test".to_string(),
            status: WebsiteStatus::Draft,
            creation_mode: CreationMode::FromScratch,
            preset_id: None,
            metadata: serde_json::json!({
                "theme": "dark",
                "layout": "grid"
            }),
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };

        assert_eq!(website.metadata["theme"], "dark");
        assert_eq!(website.metadata["layout"], "grid");
    }

    #[test]
    fn test_website_data_creation() {
        let website_id = Uuid::new_v4();
        let website_data = WebsiteData::new(website_id);

        assert_eq!(website_data.website_id, website_id);
        assert_eq!(website_data.data, serde_json::json!({}));
    }

    #[test]
    fn test_website_data_with_content() {
        let website_id = Uuid::new_v4();
        let mut website_data = WebsiteData::new(website_id);

        website_data.data = serde_json::json!({
            "projects": [
                {"name": "Project 1", "description": "A great project"},
                {"name": "Project 2", "description": "Another project"}
            ],
            "bio": "I am a developer"
        });

        assert_eq!(website_data.data["projects"].as_array().unwrap().len(), 2);
        assert_eq!(website_data.data["bio"], "I am a developer");
    }

    #[test]
    fn test_website_data_serialization() {
        let website_id = Uuid::new_v4();
        let mut website_data = WebsiteData::new(website_id);
        website_data.data = serde_json::json!({
            "title": "My Website",
            "sections": ["about", "projects", "contact"]
        });

        let serialized = serde_json::to_string(&website_data).unwrap();
        let deserialized: WebsiteData = serde_json::from_str(&serialized).unwrap();

        assert_eq!(deserialized.website_id, website_id);
        assert_eq!(deserialized.data["title"], "My Website");
    }

    #[test]
    fn test_website_clone() {
        let website = Website {
            id: Uuid::new_v4(),
            account_id: Uuid::new_v4(),
            slug: "test".to_string(),
            title: "Test".to_string(),
            tagline: "Test".to_string(),
            status: WebsiteStatus::Published,
            creation_mode: CreationMode::FromScratch,
            preset_id: None,
            metadata: serde_json::json!({"theme": "light"}),
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };

        let cloned = website.clone();
        assert_eq!(website.id, cloned.id);
        assert_eq!(website.slug, cloned.slug);
        assert_eq!(website.status, cloned.status);
    }

    #[test]
    fn test_extension_creation() {
        let extension = Extension {
            id: Uuid::new_v4(),
            name: "GitHub Sync".to_string(),
            slug: "github-sync".to_string(),
            version: "1.0.0".to_string(),
            description: "Sync projects from GitHub".to_string(),
            category: "integration".to_string(),
            enabled: true,
            default_settings: serde_json::json!({}),
            created_at: Utc::now(),
        };

        assert_eq!(extension.name, "GitHub Sync");
        assert_eq!(extension.slug, "github-sync");
        assert!(extension.enabled);
    }

    #[test]
    fn test_website_extension_creation() {
        let website_extension = WebsiteExtension {
            id: Uuid::new_v4(),
            website_id: Uuid::new_v4(),
            extension_id: Uuid::new_v4(),
            settings: serde_json::json!({"sync_interval": 3600}),
            enabled: true,
            activated_at: Utc::now(),
            updated_at: Utc::now(),
        };

        assert!(website_extension.enabled);
        assert_eq!(website_extension.settings["sync_interval"], 3600);
    }

    #[test]
    fn test_section_types() {
        let section_types = vec![
            SectionType::Hero,
            SectionType::About,
            SectionType::Projects,
            SectionType::Skills,
            SectionType::Experience,
            SectionType::Education,
            SectionType::Contact,
            SectionType::Blog,
            SectionType::Gallery,
            SectionType::Testimonials,
            SectionType::Services,
            SectionType::Pricing,
            SectionType::Faq,
            SectionType::Custom,
        ];

        for section_type in section_types {
            let serialized = serde_json::to_string(&section_type).unwrap();
            let deserialized: SectionType = serde_json::from_str(&serialized).unwrap();
            assert_eq!(section_type, deserialized);
        }
    }

    #[test]
    fn test_website_section_creation() {
        let section = WebsiteSection {
            id: Uuid::new_v4(),
            website_id: Uuid::new_v4(),
            module_id: Some(Uuid::new_v4()),
            section_type: SectionType::Projects,
            slug: "projects".to_string(),
            title: "My Projects".to_string(),
            order: 1,
            layout: SectionLayout::Grid,
            settings: serde_json::json!({}),
            data: serde_json::json!({}),
            visible: true,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };

        assert_eq!(section.section_type, SectionType::Projects);
        assert_eq!(section.layout, SectionLayout::Grid);
        assert!(section.visible);
    }

    #[test]
    fn test_preset_creation() {
        let preset = Preset {
            id: Uuid::new_v4(),
            name: "Developer Website".to_string(),
            slug: "developer-website".to_string(),
            description: "Perfect for developers to showcase their work".to_string(),
            category: "professional".to_string(),
            config: PresetConfig {
                modules: vec!["github-sync".to_string(), "analytics-tracker".to_string()],
                sections: vec![
                    PresetSectionConfig {
                        section_type: SectionType::Hero,
                        slug: "hero".to_string(),
                        title: "Welcome".to_string(),
                        order: 0,
                        layout: SectionLayout::Full,
                        settings: serde_json::json!({}),
                    },
                    PresetSectionConfig {
                        section_type: SectionType::Projects,
                        slug: "projects".to_string(),
                        title: "Projects".to_string(),
                        order: 1,
                        layout: SectionLayout::Grid,
                        settings: serde_json::json!({}),
                    },
                ],
                default_settings: serde_json::json!({"theme": "modern"}),
            },
            thumbnail_url: Some("https://example.com/preset-thumb.jpg".to_string()),
            enabled: true,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };

        assert_eq!(preset.name, "Developer Website");
        assert_eq!(preset.config.modules.len(), 2);
        assert_eq!(preset.config.sections.len(), 2);
        assert!(preset.enabled);
    }

    #[test]
    fn test_preset_config_serialization() {
        let config = PresetConfig {
            modules: vec!["github-sync".to_string()],
            sections: vec![],
            default_settings: serde_json::json!({}),
        };

        let serialized = serde_json::to_string(&config).unwrap();
        let deserialized: PresetConfig = serde_json::from_str(&serialized).unwrap();

        assert_eq!(deserialized.modules, config.modules);
    }
}
