-- ============================================================================
-- ASAP Platform - Unified Initial Schema
-- Version: 1.0.0
-- Description: Complete database schema for the ASAP platform
-- ============================================================================

-- ============================================================================
-- CORE TABLES
-- ============================================================================

-- Users table
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    tenant_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Tenants table
CREATE TABLE tenants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id UUID NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    plan TEXT NOT NULL DEFAULT 'free',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Foreign keys with DEFERRABLE constraints for circular references
ALTER TABLE tenants ADD CONSTRAINT tenants_owner_id_fkey 
    FOREIGN KEY (owner_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE users ADD CONSTRAINT users_tenant_id_fkey 
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) DEFERRABLE INITIALLY DEFERRED;

-- User data for extended information (JSONB)
CREATE TABLE user_data (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    data JSONB NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- WEBSITE TABLES
-- ============================================================================

-- Presets table (must be created before websites)
CREATE TABLE presets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    category TEXT NOT NULL DEFAULT 'general',
    config JSONB NOT NULL DEFAULT '{}',
    thumbnail_url TEXT,
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Websites table (formerly portfolios)
CREATE TABLE websites (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    slug TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    tagline TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
    metadata JSONB NOT NULL DEFAULT '{}',
    creation_mode TEXT NOT NULL DEFAULT 'from_scratch' CHECK (creation_mode IN ('from_scratch', 'from_preset')),
    preset_id UUID REFERENCES presets(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Website data (content generated by modules)
CREATE TABLE website_data (
    website_id UUID PRIMARY KEY REFERENCES websites(id) ON DELETE CASCADE,
    data JSONB NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Website sections table
CREATE TABLE website_sections (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    website_id UUID NOT NULL REFERENCES websites(id) ON DELETE CASCADE,
    module_id UUID,  -- FK added after modules table creation
    section_type TEXT NOT NULL DEFAULT 'custom',
    slug TEXT NOT NULL,
    title TEXT NOT NULL,
    "order" INT NOT NULL DEFAULT 0,
    layout TEXT NOT NULL DEFAULT 'full',
    settings JSONB NOT NULL DEFAULT '{}',
    data JSONB NOT NULL DEFAULT '{}',
    visible BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(website_id, slug)
);

-- ============================================================================
-- MODULES SYSTEM
-- ============================================================================

-- Modules registry
CREATE TABLE modules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT UNIQUE NOT NULL,
    slug TEXT UNIQUE,
    version TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    category TEXT NOT NULL DEFAULT 'general',
    icon TEXT DEFAULT NULL,
    default_settings JSONB NOT NULL DEFAULT '{}',
    config_schema JSONB DEFAULT NULL,
    sidebar_order INT DEFAULT 100,
    sidebar_label TEXT,
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Add FK from website_sections to modules
ALTER TABLE website_sections ADD CONSTRAINT website_sections_module_id_fkey
    FOREIGN KEY (module_id) REFERENCES modules(id) ON DELETE SET NULL;

-- Module configurations per tenant (legacy - kept for compatibility)
CREATE TABLE module_configs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    module_id UUID NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
    config JSONB NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(tenant_id, module_id)
);

-- Website modules junction table (many-to-many)
CREATE TABLE website_modules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    website_id UUID NOT NULL REFERENCES websites(id) ON DELETE CASCADE,
    module_id UUID NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
    settings JSONB NOT NULL DEFAULT '{}',
    enabled BOOLEAN NOT NULL DEFAULT true,
    activated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(website_id, module_id)
);

-- Tenant modules table (modules linked to tenants)
CREATE TABLE tenant_modules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    module_id UUID NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
    settings JSONB NOT NULL DEFAULT '{}',
    enabled BOOLEAN NOT NULL DEFAULT true,
    activated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(tenant_id, module_id)
);

-- ============================================================================
-- EVENTS SYSTEM
-- ============================================================================

-- Events table with retry support
CREATE TABLE events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    payload JSONB NOT NULL,
    retry_count INTEGER NOT NULL DEFAULT 0,
    failed_at TIMESTAMPTZ,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at TIMESTAMPTZ
);

-- ============================================================================
-- FILE STORAGE SYSTEM
-- ============================================================================

-- Files table to track uploaded files
CREATE TABLE files (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    filename TEXT NOT NULL,
    mime_type TEXT NOT NULL,
    original_size BIGINT NOT NULL,
    compressed_size BIGINT NOT NULL,
    file_hash TEXT NOT NULL UNIQUE,
    storage_key TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- File content table (stores compressed binary data)
CREATE TABLE file_content (
    file_id UUID PRIMARY KEY REFERENCES files(id) ON DELETE CASCADE,
    data BYTEA NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE file_content IS 'Stores compressed file binary data';
COMMENT ON COLUMN file_content.data IS 'Gzip compressed file content';

-- User storage quota table
CREATE TABLE user_storage_quota (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    total_size_used BIGINT NOT NULL DEFAULT 0,
    quota_limit BIGINT NOT NULL DEFAULT 52428800, -- 50 MB (plan standard)
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Audit table for file operations
CREATE TABLE file_operations_audit (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    file_id UUID REFERENCES files(id) ON DELETE SET NULL,
    operation TEXT NOT NULL CHECK (operation IN ('upload', 'delete', 'download')),
    ip_address INET,
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- INDEXES
-- ============================================================================

-- Users indexes
CREATE INDEX idx_users_tenant_id ON users(tenant_id);
CREATE INDEX idx_users_email ON users(email);

-- Websites indexes
CREATE INDEX idx_websites_tenant_id ON websites(tenant_id);
CREATE INDEX idx_websites_slug ON websites(slug);
CREATE INDEX idx_websites_status ON websites(status);
CREATE INDEX idx_websites_preset_id ON websites(preset_id);
CREATE INDEX idx_websites_tenant_status ON websites(tenant_id, status);

-- Website data indexes
CREATE INDEX idx_website_data_website_id ON website_data(website_id);

-- Website sections indexes
CREATE INDEX idx_website_sections_website_id ON website_sections(website_id);
CREATE INDEX idx_website_sections_order ON website_sections(website_id, "order");

-- Website modules indexes
CREATE INDEX idx_website_modules_website_id ON website_modules(website_id);
CREATE INDEX idx_website_modules_module_id ON website_modules(module_id);

-- Tenant modules indexes
CREATE INDEX idx_tenant_modules_tenant_id ON tenant_modules(tenant_id);
CREATE INDEX idx_tenant_modules_module_id ON tenant_modules(module_id);

-- Presets indexes
CREATE INDEX idx_presets_enabled ON presets(enabled);
CREATE INDEX idx_presets_category ON presets(category);

-- Events indexes
CREATE INDEX idx_events_tenant_id ON events(tenant_id);
CREATE INDEX idx_events_processed_at ON events(processed_at);
CREATE INDEX idx_events_event_type ON events(event_type);
CREATE INDEX idx_events_retry ON events(retry_count, failed_at) WHERE processed_at IS NULL AND failed_at IS NOT NULL;
CREATE INDEX idx_events_unprocessed ON events(created_at) WHERE processed_at IS NULL;
CREATE INDEX idx_events_created_at ON events(created_at DESC);
CREATE INDEX idx_events_tenant_type_time ON events(tenant_id, event_type, created_at DESC);

-- Module configs indexes
CREATE INDEX idx_module_configs_tenant_id ON module_configs(tenant_id);

-- Files indexes
CREATE INDEX idx_files_user_id ON files(user_id);
CREATE INDEX idx_files_created_at ON files(created_at);

-- File operations audit indexes
CREATE INDEX idx_file_operations_audit_user_id ON file_operations_audit(user_id);
CREATE INDEX idx_file_operations_audit_created_at ON file_operations_audit(created_at);

-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- Update timestamp trigger for user_storage_quota
CREATE OR REPLACE FUNCTION update_user_storage_quota_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_user_storage_quota_updated_at
BEFORE UPDATE ON user_storage_quota
FOR EACH ROW
EXECUTE FUNCTION update_user_storage_quota_timestamp();

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE websites ENABLE ROW LEVEL SECURITY;
ALTER TABLE website_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE website_modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE website_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE module_configs ENABLE ROW LEVEL SECURITY;

-- RLS Policy for tenant_modules
CREATE POLICY tenant_modules_tenant_isolation ON tenant_modules
    FOR ALL
    USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid);

-- ============================================================================
-- INDEX COMMENTS
-- ============================================================================

COMMENT ON INDEX idx_website_data_website_id IS 'Optimizes LEFT JOIN website_data in list/get queries';
COMMENT ON INDEX idx_websites_slug IS 'Optimizes get_public_website queries';
COMMENT ON INDEX idx_websites_status IS 'Optimizes filtering by status (published/draft)';
COMMENT ON INDEX idx_websites_tenant_status IS 'Optimizes list_websites with status filtering';
COMMENT ON INDEX idx_events_event_type IS 'Optimizes event type filtering and cleanup';
COMMENT ON INDEX idx_events_created_at IS 'Optimizes time-based event queries';
COMMENT ON INDEX idx_events_tenant_type_time IS 'Optimizes finding recent events for a tenant';
