apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: asap-staging

resources:
  - ../../base

nameSuffix: -staging

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: asap-staging
    target:
      kind: "*"

configMapGenerator:
  - name: asap-config
    behavior: merge
    literals:
      - PUBLIC_API_URL=https://api.staging.asap.cool/api
      - PUBLIC_APP_URL=https://app.staging.asap.cool
      - PUBLIC_ACCOUNTS_URL=https://accounts.staging.asap.cool

images:
  - name: asap-api
    newName: ghcr.io/asap-cool/api
    newTag: staging
  - name: asap-worker
    newName: ghcr.io/asap-cool/worker
    newTag: staging
  - name: asap-web
    newName: ghcr.io/asap-cool/web
    newTag: staging
  - name: asap-sites
    newName: ghcr.io/asap-cool/sites
    newTag: staging
  - name: asap-accounts
    newName: ghcr.io/asap-cool/accounts
    newTag: staging
